---
spring:
    rabbitmq:
        host: "${vcap.services.rabbitmq.credentials.hostname}"
        password: "${vcap.services.rabbitmq.credentials.password}"
        port: "${vcap.services.rabbitmq.credentials.port}"
        username: "${vcap.services.rabbitmq.credentials.username}"
        virtual_host: "${vcap.services.rabbitmq.credentials.virtual_host:/}"

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

resilience4j.circuitbreaker:
    instances:
        taxCalculationCircuitBreaker:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 10
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 60s
            slow-call-duration-threshold: 1s
            slow-call-rate-threshold: 50
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            recordExceptions: com.sap.slh.tax.calculation.exception.BackingServiceException

resilience4j.retry:
  instances:
    redisRetryer:
       maxRetryAttempts: 3
       waitDuration: 100ms

management.health.circuitbreakers.enabled: true

management.endpoint.chaosmonkey.enabled: true

BRS:
  credentials:
    uaa:
      clientid: ${vcap.services.BRS.credentials.uaa.clientid}
      clientsecret: ${vcap.services.BRS.credentials.uaa.clientsecret}
      xsappname: ${vcap.services.BRS.credentials.uaa.xsappname}
      repository_url: ${vcap.services.BRS.credentials.repository_url}